[localserver]
local_ip = 127.0.1
local_port = 11300

[sipserver]
sip_ip = 127.0.1
sip_port = 5061

subnode_num = 1

sip_subnode_ip1 = 127.0.1
sip_subnode_port1 = 7101
sip_subnode_poto1 = 0
sip_subnode_auth1 = 1